초기 버전의 Git 명령어 안내 추가
upnl/git-tutorial pull request #1
Opened 2022-04-02 10:52 UTC by salt26

Git 명령어 안내입니다.

2022-04-02 11:22 UTC, cseteram requested changes
작업 수고하셨습니다 🦜 문서를 길게 작성하는 게 상당히 노동력이 필요한 부분인데 많은 시간을 썼다는 게 느껴져요.

다만 세부적으로 조금 논의할 부분도 있고, 무엇보다 Git에 대해서 아무것도 모르는 분이 봤을 때 흐름을 따라잡기가 어렵다고 생각해요. 이 문서에서는 큰 흐름만 잡아주고, 세부적인 동작은 문서로 넘기는 게 좋은 접근일 것 같습니다.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +* https://git-scm.com/book/ko/v2/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-Git-%EC%84%A4%EC%B9%98
설치 섹션이 스크린샷이 많이 들어가서 긴 편인데 이걸 따로 다른 파일로 빼는 게 어떨까요?

2022-04-02 11:22 UTC, cseteram commented on README.md
> +  * 이미 Git을 사용하고 있었다면, 이 옵션을 변경하여 새로 설치해도 기존 레포지토리에는 영향을 주지 않는다.
GitHub의 기본값은 `main` 이니 그냥 `main` 이 기본값이라고 설명해도 괜찮을 거 같아요.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +  * 머지 커밋을 남기고 싶지 않고 rebase 명령을 잘 이해하고 있다면 두 번째 항목에 체크하고 "Next" 클릭해도 된다.
저는 `git pull` 을 할 때에는 항상 `--rebase` 를 붙여서 하는 편이에요.  
`origin/main` 이 로컬 브랜치인 `main` 으로 합쳐지는 게 조금 이상한 부분이 있거든요.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +  * Linux(Unix) 사용자라면 두 번째 항목에 체크하고 "Next" 클릭
Linux라면 보통은 이러한 설치 과정을 거치지 않고 터미널에서 패키지 관리자를 통해 설치할 것이니 빠져도 되는 부분인 것 같습니다.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +* 후술할 Git 명령어를 상황에 맞게 입력
Git Bash 대신 Windows Terminal을 쓰는 게 어떨까요? PowerShell이 불편하면 Git Bash 프로필을 터미널에 넣어도 되는 부분이라 Windows Terminal은 언급하는 게 좋을 거 같아요.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +   * SSH 키를 생성하고 공개키를 GitHub에 등록하는 과정은 [여기](https://www.lainyzine.com/ko/article/creating-ssh-key-for-github/)를 참조
GitHub은 HTTPS로 작업하려면 토큰을 하나 발급받아서 세팅하는 과정이 필요해요.  
그래서 SSH를 세팅하는 방법으로 안내하는 게 좋을 것 같습니다.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +   * 한번 커밋하면 되돌리기 어렵다. 신중히 입력하자.
커밋은 건드릴 방법이 많지만 이걸 푸시하는 순간 조작하기 어려워져요. 그 부분은 확실히 언급해줍시다.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +     * `git merge`에 익숙하지 않다면 이것을 하는 것을 추천하지 않는다.
저는 원격 변경사항을 땡겨올 때는 항상 `git pull --rebase`로 땡기고, 합칠 부분이 있다면 `git merge`로 합쳐요. 현재 원격 저장소의 브랜치를 트래킹하고 있다면 원격 저장소와 브랜치를 명시하지 않아도 트래킹 중인 브랜치를 가져오는데, 그런 의미에서 `git pull` 만 이야기하는 게 어떨까요?

2022-04-02 11:22 UTC, cseteram commented on README.md
> +      3. 내가 해당 scene에 새로 만든 변경사항들을 패치노트처럼 전부 기억한 다음, 원격 레포지토리의 최신 버전(내 것과 충돌한 버전)을 만들어낸 상대방의 컴퓨터에서 Unity 에디터로 해당 scene을 열어서, 내가 만들었던 변경사항들을 똑같이 수동으로 반영하고 그것으로 덮어쓰는 방법
Unity는 에셋 파일의 구조를 제대로 이해하지 않으면 수동으로 병합하는 건 안 하는 게 좋습니다. 그래서 3번 위주로 설명하면 좋을 거 같아요.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +2. `git checkout [다른 브랜치 이름]`
Git 2.25 부터 `git checkout` 명령어가 `git switch` 및 `git restore` 두 명령어로 분리되었어요. 다만 리눅스 배포판에 따라서 이전 Git 버전이 설치되어있는 경우도 있어서, 이걸 레거시 기준으로 설명할 지 아니면 최신 버전을 기준으로 설명할 지 논의해보는 게 좋을 거 같아요.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +* `git log --graph`
`git log --all --decorate --oneline --graph` 명령어도 소개하는 게 좋을 것 같아요. 예쁘게 그래프 형태로 보여줍니다.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +  * 커밋 번호를 입력할 때에는 `27a1e120c15aab3ae7d415941d86a2d2a6a0d815`처럼 전부를 입력해도 되지만, 앞의 7자리인 `27a1e12`만 입력해도 대부분의 경우 잘 동작한다.
구분 가능할 정도로만 적으면 된다고 명시해두는 게 좋을 것 같습니다. 7자리는 예시로 두고요.

2022-04-02 11:22 UTC, cseteram commented on README.md
> +   * 자세한 내용은 [여기](https://nuritech.tistory.com/33)를 참조
티스토리 문서보다는 [공식 문서](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github)를 제공하는 게 좋을 것 같습니다.

2022-04-02 11:23 UTC, cseteram commented
@tirr-c 이거 바쿠스 교육 자료 만들 때에도 비슷한 고민들을 했던 거 같은데 ㅋㅋㅋㅋ 어떻게 보십니까

2022-04-07 15:52 UTC, cseteram commented on README.md
> +* https://git-scm.com/book/ko/v2/%EC%8B%9C%EC%9E%91%ED%95%98%EA%B8%B0-Git-%EC%84%A4%EC%B9%98
윈도우도 이제 공식 패키지 관리자가 있는데 이걸로 설명하는건 어떨까요?

### Windows
`winget install -e --id Git.Git`

### Ubuntu/Debian
`sudo apt install git`

### macOS
`brew install git`

2022-06-01 06:58 UTC, salt26 commented
말씀하신 수정요청사항 거의 다 반영했습니다! 한번 확인해보시면 좋겠습니다. @cseteram

2022-06-01 09:51 UTC, cseteram approved these changes
작성하느라 수고하셨습니다 👍 

이번 PR에서 수정할 부분은 아니지만, 앞으로 이런 점들을 염두하면서 문서를 고치는 방향으로 나가면 좋을 것 같아요.

### 공식 문서 링크
저는 개인적으로 블로그 링크보다는 공식 문서 링크를 선호합니다. **특히 공식 문서에서 직접적으로 그 내용을 확인할 수 있는 경우** 더더욱 그렇습니다. 기술 블로그에 쓰인 글이 잘못되었다는 것은 아니지만, 공식 문서를 참고하는 것에 익숙해졌으면 하는 바람입니다.

### 문서의 가독성
전반적으로 리스트가 과도하게 사용이 되었고, 이로 인해서 가독성이 떨어지는 것 같아요.
마크다운 문서를 html로 서빙을 하면 좋을 거 같은데, 이 때 망치질을 해보는 게 좋을 거 같아요.

* [DocFX](https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html)
* [mdBook](https://rust-lang.github.io/mdBook/)

2022-06-01 12:00 UTC, merged

2022-06-03 08:03 UTC, cseteram commented on Install-Windows.md
> +    * 사람에 따라 머지 커밋이 기록으로 남는 게 지저분하다고 생각할 수 있다. 그러나 사실 그렇게 중요한 문제는 아니다.
FYI:

사실 `git pull` 을 기본값으로 사용하는 것은 권장되지 않습니다.  
단순히 머지 커밋만의 이유는 아니에요.