Book renewal
upnl/git-tutorial pull request #4
Opened 2022-06-03 09:13 UTC by cseteram

기존에 있던 매뉴얼을 여러 파일로 나누고, 목차를 `SUMMARY.md`에 작성하였습니다.  
그 과정에서 설치 및 세팅 부분은 내용을 조금 수정했어요.  
`README.md` 에는 이 챕터에서 어떤 내용을 다룰 것인지 간략히 이야기하고, 하위 섹션으로 풀어나가면 될 거 같아요.

빌드 결과는 액션으로 나온 아티팩트를 참고하세요.

2022-06-03 09:14 UTC, cseteram commented
https://github.com/upnl/git-tutorial/actions/runs/2433680704

2022-06-11 01:45 UTC, salt26 commented
아티팩트는 지금 모바일이라 제대로 확인이 안 되지만, 여러 개의 하위 섹션으로 분류하고 내용 수정하신 부분들은 확인하였습니다. 작업하시느라 고생 많으셨습니다!

2022-06-11 05:12 UTC, salt26 commented
문서 나누다 보면 링크가 깨질 수 있는데, 이 링크들은 나중에 문서 나누고 나서 다시 잘 동작하도록 고치면 좋을 것 같습니다!

2022-06-11 05:12 UTC, salt26 requested changes

2022-06-11 05:12 UTC, salt26 commented on src/setting/identity.md
> +`git config --global user.email "you@example.com"`
다른 부분과 통일성 있게 `[your_name]`, `[you@example.com]`으로 바꾸면 좋을 것 같습니다.

2022-06-11 05:12 UTC, salt26 commented on src/setting/identity.md
> +`your_name` 및 `you@example.com` 부분에 자신의 이름과 이메일을 적으면 된다.
다른 부분과 통일성 있게 `[your_name]`, `[you@example.com]`으로 바꾸면 좋을 것 같습니다.

2022-06-11 06:07 UTC, salt26 commented on src/setting/identity.md
> +`git config --global user.email "you@example.com"`
``` 안에 들어있는 `들도 빼주시면 감사하겠습니다!

2022-06-11 11:43 UTC, salt26 approved these changes

2022-06-11 11:44 UTC, merged